#This playbook is used to install python dependencies in centos
---
- hosts: centos
  gather_facts: no
  #sudo: yes
  pre_tasks:
- name: Bootstrap a legacy python 2.4 host
  raw: yum -y install python-simplejson
...